### ISSUE TITLE
Example dropbox link is broken

### ISSUE THREAD

**Issue by gdevenyi** [Mouse-Imaging-Centre/MRIcrotome#1]
Link in the email to the example is error 400

**Comment by jasonlerch** [comment]
Odd, that. Added it to the repo, can be viewed here:

https://rawgit.com/Mouse-Imaging-Centre/MRIcrotome/master/vignettes/figures.html

**Comment by gdevenyi** [comment]
Rawgit is dead, now use: https://htmlpreview.github.io/?https://github.com/Mouse-Imaging-Centre/MRIcrotome/blob/master/vignettes/figures.html
