### ISSUE TITLE
Crooked sagittal plane

### ISSUE THREAD

**Issue by Marina-Blmz** [Mouse-Imaging-Centre/MRIcrotome#21]
Plotting results of MincLM, everything is ok, but the sagittal plane:
 
![image](https://user-images.githubusercontent.com/50368092/146357865-b90eac7f-f236-4a5f-a664-b21b65d37492.png)

Used the following code:
`sliceSeries(nrow = 6, ncol= 2, dimension = 1, begin = dim1_begin, end = dim1_end) %>%  
  anatomy(anatVol, low=0, high=1) %>%
  addtitle("Sagittal") %>%
  overlay(mincArray(LMmodel, predictor),   
  low=lowerthreshold,
  high=upperthreshold,
  symmetric = T, alpha=0.6) %>%`

Is there any known trick to fix this? 
Any tips you could give would be much appreciated!

**Comment by gdevenyi** [comment]
Marina, this should be the same alignment as your model. Is this from a DBM? Did you bootstrap your rigid stage with a MNI model to ensure good alignment?

**Comment by Marina-Blmz** [comment]
Thaank you, Gabe! your reply gave me an idea. these are PET, but the template was created with antsMultivariateTemplateConstruction2, and then used for registration. but did i transformed the brain mask into the same space? I was stupid and i did not, from there was the error
![image](https://user-images.githubusercontent.com/50368092/146643664-853d6e50-6ae7-4395-b7fb-7d17f2747463.png)

again, thanks a million!
