### ISSUE TITLE
Excessive whitespace padding when using layout = "row" in draw()

### ISSUE THREAD

**Issue by abeaucha** [Mouse-Imaging-Centre/MRIcrotome#4]
When plotting using the layout = "row" option in draw(), the resulting graphic would be padded with excessive white space to the right of the legend, such that the actual plot was confined to the left half of the graphic. 
This issue was resolved by modifying the grobifyByRow() function such that ncol was set to 2, the title-related if-statement in the for-loop was removed, and the remaining viewport layout.pos.col arguments were set to 1 and 2 respectively.

**Comment by cfhammill** [comment]
@abeaucha do you still have the code for this fix? I'll integrate it in to the package.

EDIT: never mind, I recreated the solution in a more robust way.
