### ISSUE TITLE
theming control/theming closer to mincPlotSliceSeries?

### ISSUE THREAD

**Issue by gdevenyi** [Mouse-Imaging-Centre/MRIcrotome#9]
In mincPlotSliceSeries the background of the entire figure is black, now the legend/indicator/title are on white. I don't see any options to adjust this, is it possible?

**Comment by jasonlerch** [comment]
Not yet possible (but obviously should be).

________________________________

This e-mail may contain confidential, personal and/or health information(information which may be subject to legal restrictions on use, retention and/or disclosure) for the sole use of the intended recipient. Any review or distribution by anyone other than the person for whom it was originally intended is strictly prohibited. If you have received this e-mail in error, please contact the sender and delete all copies.

**Comment by cfhammill** [comment]
This particular theming is fixed. See the new `bgCol` argument to `grobify`. Unfortunately I didn't propagate this to `draw` yet. So you'll need:

```r
ss %>%
  grobify(bgCol = "black") %>%
  grid.draw()
```
